define("superman/components/placeholder",["require","exports","superman/lib/event","superman/lib/commonUtils"],function(require,_exports,_event,_commonUtils){"use strict";Object.defineProperty(_exports,"__esModule",{value:true});_exports.PlaceHolder=void 0;function _createForOfIteratorHelper(o){if(typeof Symbol==="undefined"||o[Symbol.iterator]==null){if(Array.isArray(o)||(o=_unsupportedIterableToArray(o))){var i=0;var F=function F(){};return{s:F,n:function n(){if(i>=o.length)return{done:true}
;return{done:false,value:o[i++]}},e:function e(_e){throw _e},f:F}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}var it,normalCompletion=true,didErr=false,err;return{s:function s(){it=o[Symbol.iterator]()},n:function n(){var step=it.next();normalCompletion=step.done;return step},e:function e(_e2){didErr=true;err=_e2},f:function f(){try{if(!normalCompletion&&it["return"]!=null
)it["return"]()}finally{if(didErr)throw err}}}}function _unsupportedIterableToArray(o,minLen){if(!o)return;if(typeof o==="string")return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);if(n==="Object"&&o.constructor)n=o.constructor.name;if(n==="Map"||n==="Set")return Array.from(n);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}function _arrayLikeToArray(arr,len){if(len==null||len>arr.length)len=arr.length
;for(var i=0,arr2=new Array(len);i<len;i++){arr2[i]=arr[i]}return arr2}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}
function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);return Constructor}function _defineProperty(obj,key,value){if(key in obj){Object.defineProperty(obj,key,{value:value,enumerable:true,configurable:true,writable:true})}else{obj[key]=value}return obj}var PlaceHolder=function(){function PlaceHolder(){_classCallCheck(this,PlaceHolder);_defineProperty(this,
"inputPlaceholder",void 0);_defineProperty(this,"placeholderUl",void 0);_defineProperty(this,"signNum",void 0);_defineProperty(this,"carouselTop",void 0);_defineProperty(this,"bigTop",void 0);_defineProperty(this,"loopNum",void 0);_defineProperty(this,"timer",void 0);this.inputPlaceholder=$(".placeholder");this.placeholderUl=$(".placeholder-ul");this.signNum=0;this.carouselTop=0;this.bigTop=0;this.loopNum=0;this.timer=0;F.addLog("superman:placeholder",["show","click"])}_createClass(PlaceHolder,[
{key:"changePlaceholder",value:function changePlaceholder(data){var placeholderUl=this.placeholderUl;data=data||JSON.parse((0,_commonUtils.getStorage)("placeholderList")||"{}");var placeholderList=data&&data.box||[];var isCarousel=data&&data.need_carousels;var str="";var _iterator=_createForOfIteratorHelper(placeholderList),_step;try{for(_iterator.s();!(_step=_iterator.n()).done;){var item=_step.value;var showText=item.show_text;if(showText.length>24){showText=showText.substring(0,23)+"..."}
str+="<li>\n                ".concat(showText," \n            </li>")}}catch(err){_iterator.e(err)}finally{_iterator.f()}placeholderUl===null||placeholderUl===void 0?void 0:placeholderUl.html(str);this.signNum=0;(0,_commonUtils.setStorage)("signNum",JSON.stringify(this.signNum));this.bigTop=-20*(placeholderList.length-1);this.carousel(isCarousel)}},{key:"carousel",value:function carousel(isCarousel){var _this=this;if(!isCarousel){return}if(this.timer){clearTimeout(this.timer)}
this.timer=setTimeout(function(){var placeholderUl=_this.placeholderUl;if(_this.carouselTop===_this.bigTop){if(_this.loopNum===2){_this.updatePlaceholder();_this.loopNum=0}else{_this.upDataUl();_this.changePlaceholder();_this.loopNum++}}else{_this.carouselTop-=20;placeholderUl===null||placeholderUl===void 0?void 0:placeholderUl.css("top",_this.carouselTop+"px");_this.signNum++;(0,_commonUtils.setStorage)("signNum",JSON.stringify(_this.signNum));_this.carousel(true)}},6500)}},{key:"upDataUl",
value:function upDataUl(){var inputPlaceholder=this.inputPlaceholder;inputPlaceholder===null||inputPlaceholder===void 0?void 0:inputPlaceholder.html('<ul class="placeholder-ul"></ul>');this.placeholderUl=$(".placeholder-ul");this.carouselTop=0}},{key:"filterPlaceholder",value:function filterPlaceholder(data){var _JSON$parse$box;var placeholderList;var signNum=JSON.parse((0,_commonUtils.getStorage)("signNum")||"0")+1;if((0,_commonUtils.getStorage)("placeholderList")){placeholderList=(0,
_commonUtils.getStorage)("placeholderList")}var oldData=placeholderList&&((_JSON$parse$box=JSON.parse(placeholderList).box)===null||_JSON$parse$box===void 0?void 0:_JSON$parse$box.slice(0,signNum));if(!oldData){return data}var idxs=[];var _iterator2=_createForOfIteratorHelper(oldData),_step2;try{for(_iterator2.s();!(_step2=_iterator2.n()).done;){var item=_step2.value;idxs.push(item.text)}}catch(err){_iterator2.e(err)}finally{_iterator2.f()}var newData=[];var repeatData=[]
;var _iterator3=_createForOfIteratorHelper(data),_step3;try{for(_iterator3.s();!(_step3=_iterator3.n()).done;){var _item=_step3.value;if(idxs.indexOf(_item.text)===-1){newData.push(_item)}else{repeatData.push(_item)}}}catch(err){_iterator3.e(err)}finally{_iterator3.f()}return newData.concat(repeatData)}},{key:"updatePlaceholder",value:function updatePlaceholder(){var _this2=this;var bsToken=$("#bsToken")&&$("#bsToken").val()||"";$.ajax({url:"/home/async/boxrec?bsToken="+bsToken,type:"GET",
data:"",headers:{"Content-Type":"application/json"},traditional:true,success:function success(data){if(!data){return}data=data.data;data.box=data&&data.box&&_this2.filterPlaceholder(data.box);(0,_commonUtils.setStorage)("placeholderList",JSON.stringify(data));_this2.upDataUl();_this2.changePlaceholder(data)}})}},{key:"clearPlaceholder",value:function clearPlaceholder(){var inputPlaceholder=this.inputPlaceholder;var bdsugDisplay=$(".bdsug").css("display");if(bdsugDisplay==="block"){if(this.timer
){clearTimeout(this.timer)}inputPlaceholder===null||inputPlaceholder===void 0?void 0:inputPlaceholder.remove()}}},{key:"init",value:function init(){var _this3=this;if(!window.s_session.isLogin){return}var nodeSample=bds&&bds.comm&&bds.comm.nodeSample||"";var boxRec=nodeSample.indexOf("need_carousels")>-1||nodeSample.indexOf("no_need_carousels")>-1;if(!boxRec){return}(0,_event.fire)("superman:placeholder","show",{clickType:"show"});this.updatePlaceholder();var input=document.getElementById("kw")
;var inputPlaceholder=this.inputPlaceholder;input===null||input===void 0?void 0:input.addEventListener("input",function(){inputPlaceholder===null||inputPlaceholder===void 0?void 0:inputPlaceholder.css("display","none")});input===null||input===void 0?void 0:input.addEventListener("click",function(){if(_this3.timer){clearTimeout(_this3.timer)}});input===null||input===void 0?void 0:input.addEventListener("blur",function(){if(!(0,_commonUtils.getStorage)("placeholderList")){return}
var data=JSON.parse((0,_commonUtils.getStorage)("placeholderList")||"{}");var isCarousel=data.need_carousels;_this3.carousel(isCarousel)});input===null||input===void 0?void 0:input.addEventListener("keydown",function(event){if(event.keyCode===38||event.keyCode===40){_this3.clearPlaceholder()}})}},{key:"destroy",value:function destroy(){if(this.timer){clearTimeout(this.timer)}}}]);return PlaceHolder}();_exports.PlaceHolder=PlaceHolder});